CREATE TABLE IF NOT EXISTS ny_products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    vendor_sku_code VARCHAR(255),
    mfg_sku_code VARCHAR(255),
    sku_name VARCHAR(255) NOT NULL,
    mrp VARCHAR(255) NOT NULL,
    sale_price VARCHAR(255) NOT NULL,
    base_cost VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    last_update_date VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    color VARCHAR(255),
    size VARCHAR(255),
    weight VARCHAR(255),
    length VARCHAR(255),
    width VARCHAR(255),
    height VARCHAR(255),
    serial_tracking VARCHAR(1),
    seller_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sku_token (sku, token)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(255) NOT NULL UNIQUE,
    order_status VARCHAR(50) NOT NULL,
    order_date TIMESTAMP NOT NULL,
    order_last_update_date TIMESTAMP NOT NULL,
    on_hold VARCHAR(1) NOT NULL DEFAULT '0',
    seller_id VARCHAR(255) NOT NULL,
    seller_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_seller_type (seller_type),
    INDEX idx_seller_id (seller_id),
    INDEX idx_order_status (order_status),
    INDEX idx_order_last_update_date (order_last_update_date),
    INDEX idx_seller_type_seller_id (seller_type, seller_id)
); 