CREATE TABLE IF NOT EXISTS ny_products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    vendor_sku_code VARCHAR(255),
    mfg_sku_code VARCHAR(255),
    sku_name VARCHAR(255) NOT NULL,
    mrp VARCHAR(255) NOT NULL,
    sale_price VARCHAR(255) NOT NULL,
    base_cost VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    last_update_date VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    color VARCHAR(255),
    size VARCHAR(255),
    weight VARCHAR(255),
    length VARCHAR(255),
    width VARCHAR(255),
    height VARCHAR(255),
    serial_tracking VARCHAR(1),
    seller_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sku_token (sku, token)
); 