CREATE TABLE IF NOT EXISTS ny_products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    vendor_sku_code VARCHAR(255),
    mfg_sku_code VARCHAR(255),
    sku_name VARCHAR(255) NOT NULL,
    mrp VARCHAR(255) NOT NULL,
    sale_price VARCHAR(255) NOT NULL,
    base_cost VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    last_update_date VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    color VARCHAR(255),
    size VARCHAR(255),
    weight VARCHAR(255),
    length VARCHAR(255),
    width VARCHAR(255),
    height VARCHAR(255),
    serial_tracking VARCHAR(1),
    seller_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sku_token (sku, token)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(255) NOT NULL UNIQUE,
    order_status VARCHAR(50) NOT NULL,
    order_date TIMESTAMP NOT NULL,
    order_last_update_date TIMESTAMP NOT NULL,
    on_hold VARCHAR(1) NOT NULL DEFAULT '0',
    seller_id VARCHAR(255) NOT NULL,
    seller_type VARCHAR(50),
    sla VARCHAR(255),
    customer_name VARCHAR(255),
    payment_method VARCHAR(50),
    order_amount VARCHAR(50),
    order_currency VARCHAR(10),
    order_tax_amount VARCHAR(50),
    shipping_charge VARCHAR(50),
    discount_amount VARCHAR(50),
    disc_coupon_code VARCHAR(255),
    store_credit VARCHAR(50),
    gv_amount VARCHAR(50),
    cod_charge VARCHAR(50),
    address1 VARCHAR(500),
    address2 VARCHAR(500),
    address3 VARCHAR(500),
    phone VARCHAR(50),
    email VARCHAR(100),
    country_code VARCHAR(10),
    state VARCHAR(100),
    city VARCHAR(100),
    pin_code VARCHAR(20),
    bill_to_name VARCHAR(255),
    bill_address1 VARCHAR(500),
    bill_address2 VARCHAR(500),
    bill_address3 VARCHAR(500),
    bill_phone VARCHAR(50),
    bill_email VARCHAR(100),
    bill_country_code VARCHAR(10),
    bill_state VARCHAR(100),
    bill_city VARCHAR(100),
    bill_zip_code VARCHAR(20),
    cancel_remark VARCHAR(500),
    reason_for_cancellation VARCHAR(500),
    priority VARCHAR(50),
    master_order_no VARCHAR(255),
    gstin VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_seller_type (seller_type),
    INDEX idx_seller_id (seller_id),
    INDEX idx_order_status (order_status),
    INDEX idx_order_last_update_date (order_last_update_date),
    INDEX idx_seller_type_seller_id (seller_type, seller_id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT,
    order_no VARCHAR(255) NOT NULL,
    line_no VARCHAR(50),
    delivery_mode VARCHAR(50),
    sku_code VARCHAR(255),
    sku_name VARCHAR(255),
    order_qty VARCHAR(50),
    rejected_qty VARCHAR(50),
    cancelled_qty VARCHAR(50),
    shipped_qty VARCHAR(50),
    returned_qty VARCHAR(50),
    delivered_qty VARCHAR(50),
    line_amount VARCHAR(50),
    line_tax_amount VARCHAR(50),
    unit_price VARCHAR(50),
    mrp VARCHAR(50),
    discount_amount VARCHAR(50),
    shipping_charge VARCHAR(50),
    cod_charge VARCHAR(50),
    invoice_no VARCHAR(255),
    trans_code VARCHAR(50),
    trans_name VARCHAR(255),
    awb_no VARCHAR(255),
    imei_nos VARCHAR(255),
    confirm_date TIMESTAMP,
    gv_amount VARCHAR(50),
    store_credit VARCHAR(50),
    line_status VARCHAR(50),
    cst VARCHAR(50),
    vat VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_order_no (order_no)
); 